In [1]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

with mlflow.start_run():
    mlflow.log_param("param1", 15)
    mlflow.log_metric("metric1", 0.89)

🏃 View run selective-trout-512 at: http://127.0.0.1:5000/#/experiments/0/runs/83d4fcbd834a4b3fb3ea513ce7d6c8e9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/0

In [2]:
#creating baseline model

import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv')
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [4]:
df.dropna(inplace=True)

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df = df[~(df['clean_comment'].str.strip() == '')]

In [7]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [8]:
# Ensure necessary NLTK data is downloaded
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ayushi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ayushi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [9]:
# Define the preprocessing function
def preprocess_comment(comment):
    # Convert to lowercase
    comment = comment.lower()

    # Remove trailing and leading whitespaces
    comment = comment.strip()

    # Remove newline characters
    comment = re.sub(r'\n', ' ', comment)

    # Remove non-alphanumeric characters, except punctuation
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)

    # Remove stopwords but retain important ones for sentiment analysis
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])

    return comment

In [10]:
# Apply the preprocessing function to the 'clean_comment' column
df['clean_comment'] = df['clean_comment'].apply(preprocess_comment)

In [11]:
df.head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1

In [12]:
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
# Step 1: Vectorize the comments using Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=10000)  # Bag of Words model with a limit of 1000 features

In [14]:
X = vectorizer.fit_transform(df['clean_comment']).toarray()
y = df['category']  # Assuming 'sentiment' is the target variable (0 or 1 for binary classification)

In [15]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(36793, 10000))

In [16]:
X.shape

(36793, 10000)

In [17]:
y

0        1
1        1
2       -1
3        0
4        1
        ..
37244    0
37245    1
37246    0
37247    1
37248    0
Name: category, Length: 36793, dtype: int64

In [18]:
y.shape

(36793,)

In [19]:
# Step 2: Set up the MLflow tracking server
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [20]:
# Set or create an experiment
mlflow.set_experiment("RF Baseline")

<Experiment: artifact_location='mlflow-artifacts:/1', creation_time=1776619339907, experiment_id='1', last_update_time=1776619339907, lifecycle_stage='active', name='RF Baseline', tags={}, trace_location=None, workspace='default'>

In [21]:
!pip install boto3

Requirement already satisfied: boto3 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (1.42.91)
Requirement already satisfied: botocore<1.43.0,>=1.42.91 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from boto3) (1.42.91)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from boto3) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from boto3) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from botocore<1.43.0,>=1.42.91->boto3) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from botocore<1.43.0,>=1.42.91->boto3) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.91->boto3) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
!pip install awscli

Requirement already satisfied: awscli in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (1.44.81)
Requirement already satisfied: botocore==1.42.91 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (1.42.91)
Requirement already satisfied: docutils<=0.19,>=0.18.1 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (0.19)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (0.16.0)
Requirement already satisfied: PyYAML<6.1,>=3.10 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (6.0.3)
Requirement already satisfied: colorama<0.4.7,>=0.2.5 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (0.4.6)
Requirement already satisfied: rsa<4.8,>=3.1.2 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from awscli) (4.7.2)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from botocore==1.42.91->awscli) (1.1.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from botocore==1.42.91->awscli) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from botocore==1.42.91->awscli) (2.5.0)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from rsa<4.8,>=3.1.2->awscli) (0.6.3)
Requirement already satisfied: six>=1.5 in c:\users\ayushi\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.42.91->awscli) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
# Step 1: Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Step 2: Define and train a Random Forest baseline model using a simple train-test split
with mlflow.start_run() as run:

    # Run tags
    mlflow.set_tag("mlflow.runName", "RandomForest_Baseline_TrainTestSplit")
    mlflow.set_tag("experiment_type", "baseline")
    mlflow.set_tag("model_type", "RandomForestClassifier")
    mlflow.set_tag(
        "description",
        "Baseline RandomForest model for sentiment analysis using Bag of Words (BoW)"
    )

    # Log vectorizer params
    mlflow.log_param("vectorizer_type", "CountVectorizer")
    mlflow.log_param("vectorizer_max_features", vectorizer.max_features)

    # Model params
    n_estimators = 200
    max_depth = 15

    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)

    # Train model
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Accuracy
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", accuracy)

    # Classification report
    classification_rep = classification_report(
        y_test,
        y_pred,
        output_dict=True
    )

    for label, metrics in classification_rep.items():
        if isinstance(metrics, dict):
            for metric, value in metrics.items():
                mlflow.log_metric(f"{label}_{metric}", value)

    # Confusion Matrix
    conf_matrix = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")

    # Save locally
    plt.savefig("confusion_matrix.png")
    plt.close()

    # Correct artifact logging
    mlflow.log_artifact("confusion_matrix.png")

    # Save model
    mlflow.sklearn.log_model(model, "random_forest_model")

    # Save dataset
    df.to_csv("dataset.csv", index=False)
    mlflow.log_artifact("../data/dataset.csv")

# Final output
print(f"Accuracy: {accuracy}")

2026/04/20 09:57:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/20 09:57:31 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run RandomForest_Baseline_TrainTestSplit at: http://127.0.0.1:5000/#/experiments/1/runs/4076b8c948734b0486d07e0b2553121a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
Accuracy: 0.6479141187661367

In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       1.00      0.01      0.02      1650
           0       0.68      0.81      0.74      2555
           1       0.62      0.85      0.72      3154

    accuracy                           0.65      7359
   macro avg       0.77      0.56      0.49      7359
weighted avg       0.73      0.65      0.57      7359

In [37]:
df.to_csv('reddit_preprocessing.csv', index=False)

In [38]:
pd.read_csv('../data/reddit_preprocessing.csv').head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1